- name: Install Required Packages
  ansible.builtin.apt:
    pkg:
    - python3-pip
    - python3-dev
    - libpq-dev
    - curl
    - ufw
    - nginx
  become: yes
  become_user: root

- name: ensure file exists
  copy:
    content: ""
    dest: /home/asim/added-by-ansible
    force: no
    group: asim
    owner: asim
    mode: 0555
